// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Vy5XhoITsJg-Uju5UlBkBpF1Xqij1EQ',
    appId: '1:126760702891:web:884a07564b55f7b5e438ee',
    messagingSenderId: '126760702891',
    projectId: 'agrico-4ab4d',
    authDomain: 'agrico-4ab4d.firebaseapp.com',
    storageBucket: 'agrico-4ab4d.firebasestorage.app',
    measurementId: 'G-K35P0NSVX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_lSD0mwXbE8Ae11APi5IRpGCB3WE4WUE',
    appId: '1:126760702891:android:42b2f20bc85c57e2e438ee',
    messagingSenderId: '126760702891',
    projectId: 'agrico-4ab4d',
    storageBucket: 'agrico-4ab4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwupnxtXIRIdX7H39VIxOY_hPX_tF8vMg',
    appId: '1:126760702891:ios:eb8b68f7ae1ea050e438ee',
    messagingSenderId: '126760702891',
    projectId: 'agrico-4ab4d',
    storageBucket: 'agrico-4ab4d.firebasestorage.app',
    iosClientId: '126760702891-e0os1q3vc386f17ss505fclargc87qfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwupnxtXIRIdX7H39VIxOY_hPX_tF8vMg',
    appId: '1:126760702891:ios:eb8b68f7ae1ea050e438ee',
    messagingSenderId: '126760702891',
    projectId: 'agrico-4ab4d',
    storageBucket: 'agrico-4ab4d.firebasestorage.app',
    iosClientId: '126760702891-e0os1q3vc386f17ss505fclargc87qfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Vy5XhoITsJg-Uju5UlBkBpF1Xqij1EQ',
    appId: '1:126760702891:web:697dfec01d47abbfe438ee',
    messagingSenderId: '126760702891',
    projectId: 'agrico-4ab4d',
    authDomain: 'agrico-4ab4d.firebaseapp.com',
    storageBucket: 'agrico-4ab4d.firebasestorage.app',
    measurementId: 'G-C842JGYVRN',
  );

}